image: "python:3.10-slim"

before_script:
  - python3 --version


stages:
  - analysis
  - test

pep8:
  stage: analysis
  script:
    - pip install pycodestyle
    - pycodestyle teVeoapp/*.py


test:
  stage: test
  script:
    - python3 -m venv venv/
    - source venv/bin/activate
    - pip install -r requirements.txt
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test