image: "python:3.10-slim"

before_script:
  - python3 --version


stages:
  - analysis
  - test

pep8:
  stage: analysis
  script:
    - pip install pycodestyle
    - pycodestyle practicaFinal/teVeoapp/*.py
    - pip install pep8
    - pep8 practicaFinal/teVeoapp/*.py


test:
  stage: test
  script:
    - python3 -m venv venv/
    - source venv/bin/activate
    - pip install django
    - python3 practicaFinal/manage.py makemigrations
    - python3 practicaFinal/manage.py migrate
    - python3 practicaFinal/manage.py test